# Generated by Django 3.1.4 on 2021-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldwayverification',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='goldwayverification',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
