# Generated by Django 3.1.4 on 2021-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='internal_id',
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_girdle_min_grade_final',
            field=models.CharField(blank=True, choices=[('ETN', 'Extremely Thin'), ('VTN', 'Very Thin'), ('THN', 'Thin'), ('MED', 'Medium'), ('STK', 'Slightly Thick'), ('THK', 'Thick'), ('VTK', 'Very Thick'), ('ETK', 'Extremely Thick'), ('ETN TO VTN', 'Extremely Thin to Very Thin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='girdle_max_grade',
            field=models.CharField(choices=[('ETN', 'Extremely Thin'), ('VTN', 'Very Thin'), ('THN', 'Thin'), ('MED', 'Medium'), ('STK', 'Slightly Thick'), ('THK', 'Thick'), ('VTK', 'Very Thick'), ('ETK', 'Extremely Thick'), ('ETN TO VTN', 'Extremely Thin to Very Thin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stone',
            name='girdle_min_grade',
            field=models.CharField(choices=[('ETN', 'Extremely Thin'), ('VTN', 'Very Thin'), ('THN', 'Thin'), ('MED', 'Medium'), ('STK', 'Slightly Thick'), ('THK', 'Thick'), ('VTK', 'Very Thick'), ('ETK', 'Extremely Thick'), ('ETN TO VTN', 'Extremely Thin to Very Thin')], max_length=10),
        ),
    ]
