# Generated by Django 3.0.6 on 2020-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelView',
            fields=[
            ],
            options={
                'verbose_name': 'Step 2. View parcel info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grading.parcel',),
        ),
        migrations.AlterModelOptions(
            name='closeoutreceipt',
            options={'verbose_name': 'Step 3. View receipts and close out receipt on stone release'},
        ),
        migrations.AlterModelOptions(
            name='createreceipt',
            options={'verbose_name': 'Step 1. Create receipt for stone intake'},
        ),
    ]
