# Generated by Django 3.1.4 on 2022-03-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
