# Generated by Django 3.0.6 on 2020-06-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'verbose_name': 'Parcel- Check Inventory'},
        ),
        migrations.AlterModelOptions(
            name='split',
            options={'verbose_name': 'Split parcel into smaller parcels or individual stone'},
        ),
        migrations.AlterModelOptions(
            name='stone',
            options={'verbose_name': 'Stone- Check Inventory'},
        ),
    ]
