# Generated by Django 3.1.4 on 2021-01-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grading", "0002_auto_20210125_0913")]

    operations = [
        migrations.AlterField(
            model_name="stone",
            name="inclusions",
            field=models.ManyToManyField(related_name="inclusions", to="grading.Inclusion"),
        )
    ]
