# Generated by Django 3.1.4 on 2021-11-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20211104_0636'),
        ('grading', '0002_auto_20211104_0638'),
    ]

    operations = [
    ]
