# Generated by Django 3.0.6 on 2020-06-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20200602_0133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParcelView',
        ),
        migrations.CreateModel(
            name='VerboseParcel',
            fields=[
            ],
            options={
                'verbose_name': 'Step 2. View parcel info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('grading.parcel',),
        ),
    ]
