# Generated by Django 3.1.4 on 2021-09-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20210928_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='gia_diamond_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
