# Generated by Django 3.1.4 on 2021-09-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20210916_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stone',
            old_name='basic_girdle_characteristic_1',
            new_name='basic_girdle_condition_1',
        ),
        migrations.RenameField(
            model_name='stone',
            old_name='basic_girdle_characteristic_2',
            new_name='basic_girdle_condition_2',
        ),
        migrations.RenameField(
            model_name='stone',
            old_name='basic_girdle_characteristic_3',
            new_name='basic_girdle_condition_3',
        ),
        migrations.RenameField(
            model_name='stone',
            old_name='basic_girdle_characteristic_final',
            new_name='basic_girdle_condition_final',
        ),
    ]
