# Generated by Django 3.0.6 on 2020-08-17 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20200816_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='crown_angle',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.11, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='cut',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='girdle_thickness',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='stone',
            name='measurement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stone',
            name='pavilion_depth_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.11, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='polish',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='shape',
            field=models.CharField(default='Round Brilliant', max_length=15),
        ),
        migrations.AddField(
            model_name='stone',
            name='symmetry',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='table_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.11, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stone',
            name='total_depth_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.11, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
