# Generated by Django 3.1.4 on 2021-09-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_stone_gia_diamond_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='gia_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
