# Generated by Django 3.1.4 on 2021-01-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grading", "0003_auto_20210125_0926")]

    operations = [
        migrations.AlterField(
            model_name="stone",
            name="final_sarine_cut",
            field=models.CharField(
                blank=True,
                choices=[("EX", "Excellent"), ("VG", "Very Good"), ("GOOD", "Good"), ("F", "Fair"), ("P", "Poor")],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stone",
            name="final_sheryl_cut",
            field=models.CharField(
                blank=True,
                choices=[("EX", "Excellent"), ("VG", "Very Good"), ("GOOD", "Good"), ("F", "Fair"), ("P", "Poor")],
                max_length=4,
                null=True,
            ),
        ),
    ]
