# Generated by Django 3.1.4 on 2022-01-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_auto_20211210_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giaverification',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='giaverification',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='goldwayverification',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_culet_characteristic_1',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_culet_characteristic_2',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_culet_characteristic_3',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_culet_characteristic_final',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gia_culet_characteristic_1',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gia_culet_characteristic_2',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gia_culet_characteristic_3',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gia_culet_characteristic_final',
            field=models.CharField(blank=True, choices=[('N', 'None'), ('ABR', 'ABR'), ('SAB', 'Slightly Abraded'), ('CH', 'Chipped'), ('VSAB', 'Very Slightly Abraded')], max_length=5, null=True),
        ),
    ]
