# Generated by Django 3.1.4 on 2022-02-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_auto_20220110_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='macro_filename',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stone',
            name='nano_filename',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
