# Generated by Django 3.1.4 on 2022-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_auto_20220110_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True),
        ),
    ]
