# Generated by Django 3.1.4 on 2022-01-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_auto_20220110_1810'),
        ('grading', '0003_merge_20211104_1325'),
    ]

    operations = [
    ]
