# Generated by Django 3.1.4 on 2022-02-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_auto_20220208_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='external_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
