# Generated by Django 3.1.4 on 2022-02-25 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_auto_20220211_0209'),
        ('grading', '0006_merge_20220111_0924'),
        ('grading', '0006_auto_20220221_2014'),
    ]

    operations = [
    ]
