# Generated by Django 3.1.4 on 2022-02-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_merge_20220225_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='basic_fluorescence_1',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_fluorescence_2',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_fluorescence_3',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='basic_fluorescence_final',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gw_fluorescence',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gw_fluorescence_adjusted_1',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gw_fluorescence_adjusted_2',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gw_fluorescence_adjusted_3',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='gw_fluorescence_adjusted_final',
            field=models.CharField(blank=True, choices=[('VS', 'Very Strong'), ('S', 'Strong'), ('M', 'Medium'), ('F', 'Faint'), ('N', 'None'), ('MG', 'Medium Green'), ('MW', 'Medium White'), ('MB', 'Medium Blue'), ('MY', 'Medium Yellow'), ('VSB', 'Very Strong Blue'), ('VSY', 'Very Strong Yellow'), ('VSW', 'Very Strong White'), ('VSG', 'Very Strong Green'), ('SB', 'Strong Blue'), ('SY', 'Strong Yellow'), ('SW', 'Strong White'), ('SG', 'Strong Green')], max_length=4, null=True),
        ),
    ]
