# Generated by Django 3.1.4 on 2022-03-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_auto_20220225_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
