# Generated by Django 3.0.6 on 2020-05-20 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=15)),
                ('intake_date', models.DateTimeField(auto_now_add=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('remarks', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('S', 'Supplier'), ('C', 'Customer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
                ('reference_price_per_carat', models.PositiveIntegerField()),
                ('total_carats', models.DecimalField(decimal_places=3, max_digits=5)),
                ('total_pieces', models.IntegerField()),
                ('rejected_carats', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('rejected_pieces', models.IntegerField(blank=True, null=True)),
                ('basic_graded_carats', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('basic_graded_pieces', models.IntegerField(blank=True, null=True)),
                ('triple_verified_carats', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('triple_verified_pieces', models.IntegerField(blank=True, null=True)),
                ('total_price_paid', models.IntegerField(blank=True, null=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Consignment')),
            ],
        ),
        migrations.AddField(
            model_name='consignment',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.Entity'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='intake_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_intake', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consignment',
            name='release_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_release', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuthorizedPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('hkid', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='EndConsignment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customers.consignment',),
        ),
    ]
