# Generated by Django 3.0.6 on 2020-06-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseOutReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'Step 3. View receipts and close out receipt on stone release',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.receipt',),
        ),
        migrations.CreateModel(
            name='CreateReceipt',
            fields=[
            ],
            options={
                'verbose_name': 'Step 1. Create receipt for stone intake',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.receipt',),
        ),
        migrations.CreateModel(
            name='ParcelRejection',
            fields=[
            ],
            options={
                'verbose_name': 'Step 2. View parcel info and record rejection',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('purchases.parcel',),
        ),
    ]
